name: Daily GitHub Report
on:
  schedule:
    - cron: '0 11 * * *' # every day at 11:00 UTC
  workflow_dispatch:

jobs:
  report:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SMTP_USER: ${{ secrets.SMTP_USER }}
      SMTP_PASS: ${{ secrets.SMTP_PASS }}
      EMAIL_FROM: ${{ env.EMAIL_FROM }}
      EMAIL_TO: ${{ env.EMAIL_TO }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install requests
      - name: Run the report script
        run: python github_digest.py
